---

os_tuning:
  # Swappiness controls the relative weight given to swapping out runtime memory.
  # default OS value: 20
  - name: vm.swappiness
    value: 1
  # This sets the default OS receive buffer size for all types of connections.
  # default OS value: 124928
  - name: net.core.rmem_default
    value: 124928
  # This sets the max OS receive buffer size for all types of connections.
  # default OS value: 2048000
  - name: net.core.rmem_max
    value: 2048000
  # This sets the default OS send buffer size for all types of connections
  # default OS value: 124928
  - name: net.core.wmem_default
    value: 124928
  # This sets the max OS send buffer size for all types of connections.
  # default OS value: 2048000
  - name: net.core.wmem_max
    value: 2048000
  # TCP Autotuning setting. "The first value tells the kernel the minimum receive buffer for each TCP connection, and
  # this buffer is always allocated to a TCP socket, even under high pressure on the system. ... The second value
  # specified tells the kernel the default receive buffer allocated for each TCP socket. This value overrides the
  # /proc/sys/net/core/rmem_default value used by other protocols. ... The third and last value specified in this
  # variable specifies the maximum receive buffer that can be allocated for a TCP socket."
  # default OS value: 4096 87380 4194304
  - name: net.ipv4.tcp_rmem
    value: 4096 87380 4194304
  # TCP Autotuning setting. "This variable takes 3 different values which holds information on how much TCP sendbuffer
  # memory space each TCP socket has to use. Every TCP socket has this much buffer space to use before the buffer is
  # filled up. Each of the three values are used under different conditions. ... The first value in this variable tells
  # the minimum TCP send buffer space available for a single TCP socket. ... The second value in the variable tells us
  # the default buffer space allowed for a single TCP socket to use. ... The third value tells the kernel the maximum
  # TCP send buffer space."
  # default OS value: 4096 16384 4194304
  - name: net.ipv4.tcp_wmem
    value: 4096 16384 4194304
  # Maximal number of timewait sockets held by the system simultaneously
  # default OS value: 262144
  - name: net.ipv4.tcp_max_tw_buckets
    value: 262144
  # Increase the number of outstanding syn requests allowed.
  # default OS value: 1024
  - name: net.ipv4.tcp_max_syn_backlog
    value: 1024
  # the OOM killer simply kills the task that triggered the out-of-memory condition.
  # default OS value: No value, no key
#  - name: vm.oom.kill_allocation_task
#    value: 1
  # the maximum number of memory map areas a process may have
  # default OS value: 200000
  - name: vm.max_map_count
    value: 262144
  # how often the pdflush/flush/kdmflush processes wake up and check to see if work needs to be done.
  # default OS value: 500
#  - name: vm.dirty_writeback_centisecs
#    value: 500
  # how long something can be in cache before it needs to be written.
  # default OS value: 500
#  - name: vm.dirty_expire_centisecs
#    value: 500
  # the absolute maximum amount of system memory that can be filled with dirty pages before everything must get committed
  # to disk.
  # default OS value: 60
#  - name: vm.dirty_ratio
#    value: 60
  # the percentage of system memory that can be filled with “dirty” pages — memory pages that still need to be written
  # to disk — before the pdflush/flush/kdmflush background processes kick in to write it to disk.
  # default OS value: 5
#  - name: vm.dirty_background_ratio
#    value: 5

...
