---

# user/ group to run neo4j
user: neo4j
group: neo4j

base_directory: /neo4j
version: 5.10.0

network_host: 0.0.0.0
memory: 256m

db_name: neo4j
login: neo4j
password: test

# Required version of Java
java_version: 17

...
